config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users

  resources :ballads do
    collection { post :import }
  end

  resources :ballad_imports

  resources :notifications, path: 'admin/notifications'

  get 'home' => 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'history' => 'static_pages#history'

  get 'links' => 'static_pages#links'

  get 'data' => 'data_vis#home'

  get 'data/popularity' => 'data_vis#popularity'

  get 'data/timeline' => 'data_vis#timeline'

  get 'all' => 'static_pages#all'

  get 'admin' => 'admin_pages#home'

  get 'admin/music-data' => 'admin_pages#music_data'

  get 'admin/ballad-data' => 'admin_pages#ballad_data'

  get 'admin/songs-data' => 'admin_pages#songs_data'

end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /admin/notifications
  # GET /admin/notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /admin/notifications/1
  # GET /admin/notifications/1.json
  def show
  end

  # GET /admin/notifications/new
  def new
    @notification = Notification.new
  end

  # GET /admin/notifications/1/edit
  def edit
  end

  # POST /admin/notifications
  # POST /admin/notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/notifications/1
  # PATCH/PUT /admin/notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/notifications/1
  # DELETE /admin/notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:text, :expires_on)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_with(model: notification, local: true) do |form| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :expires_on %>
    <%= form.datetime_local_field :expires_on, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= link_to 'Cancel', notifications_path %>

<%= render 'form', notification: @notification %>

app/views/notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notifications</h1>

<%= link_to "Add Notification", new_notification_path, class: "btn btn-primary file-button" %>

<br>
<br>

<% @notifications.each do |notification| %>
  <p>
  <%= link_to notification.text, notification_path(notification) %> 
  <% if notification.expires_on %>
   - <%= notification.expires_on.strftime("%-m/%-d/%Y: %H:%M %Z") %> 
  <% end %>
  </p>
<% end %>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= link_to 'Cancel', notifications_path %>

<%= render 'form', notification: @notification %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @notification.text %>
</p>

<p>
  <strong>Expires on:</strong>
  <%= @notification.expires_on %>
</p>

<%= link_to 'Back', notifications_path %> |
<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Delete', notification_path(@notification), method: :delete, data: { confirm: "Are you sure?" } %>