config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users

  resources :ballads do
    collection { post :import }
  end

  resources :ballad_imports

  resources :notifications, path: 'admin/notifications'

  get 'home' => 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'history' => 'static_pages#history'

  get 'links' => 'static_pages#links'

  get 'data' => 'data_vis#home'

  get 'data/popularity' => 'data_vis#popularity'

  get 'data/timeline' => 'data_vis#timeline'

  get 'all' => 'static_pages#all'

  get 'admin' => 'admin_pages#home'

  get 'admin/music-data' => 'admin_pages#music_data'

  get 'admin/ballad-data' => 'admin_pages#ballad_data'

  get 'admin/songs-data' => 'admin_pages#songs_data'

end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController

  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction
  
  def home
  end

  def music_data
    @ballads = ChildBallad.order(:number)
  end

  def ballad_data
    @ballad = ChildBallad.find(params[:id])
    @songs = @ballad.songs
  end

  def songs_data
    @songs = Song.search(song_params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 50, :page => song_params[:page])
  end

  private
  
    def sort_column
      Song.column_names.include?(song_params[:sort]) ? song_params[:sort] : "ballad_id"
    end
    
    def sort_direction
      %w[asc desc].include?(song_params[:direction]) ? song_params[:direction] : "asc"
    end

    def song_params
      params.permit(:ballad_id, :artist, :title, :source, :release_year, :length, :have, :search, :page, :sort, :direction)
    end
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/views/admin_pages/_songs.html.erb
<%= hidden_field_tag :direction, params[:direction] %> 
<%= hidden_field_tag :sort, params[:sort] %> 
<table class="pretty table">
  <tr>
    <th><%= sortable "Number", "ballad_id" %></th>
    <th><%= sortable "Artist", "artist" %></th>
    <th><%= sortable "Title", "title" %></th>
    <th><%= sortable "Source", "source" %></th>
    <th><%= sortable "Release Year", "release_year" %></th>
    <th><%= sortable "Length", "length" %></th>
  </tr>
  <% for song in @songs %>
    <tr>
      <td><%= song.ballad_id%></td>
      <td><%= song.artist%></td>
      <td><%= link_to song.title, ballad_path(:id => song.id) %> </td>
      <td><%= song.source%></td>
      <td><%= song.release_year%></td>
      <% if song.length.to_s.length >= 2 %>
        <td><%= song.length.to_s.insert(-3, ':')%></td>
      <% else %>
        <td><%= song.length%></td>
      <% end %>
    </tr>
  <% end %>
</table>
<%= will_paginate @songs %>

app/views/admin_pages/ballad_data.html.erb
<h1><%= @ballad.name %></h1>
  <br>
<% @songs.each do |song| %>
  <p>
  <%= song.ballad_id %>: 
  <%= link_to song.title, ballad_path(song) %> 
  <br>
  <%= song.artist %>
  <%= song.release_year %>
  </p>
<% end %>

app/views/admin_pages/home.html.erb
<h1>Child Ballad Database Administration</h1>
<p>This portion of the site is for admins only and allows for the editing and uploading of data relating to the Child Ballads.</p>

app/views/admin_pages/music_data.html.erb
<h1>Child Ballads</h1>

<%= link_to "Add Recording", new_ballad_path, class: "btn btn-primary file-button" %>

<br>
<br>

<% @ballads.each do |ballad| %>
  <p>
  <%= ballad.number %>: 
  <%= link_to ballad.name, admin_ballad_data_path(:id => ballad.number) %> 
  </p>
<% end %>

app/views/admin_pages/songs_data.html.erb
<h1>All Child Ballad Renditions</h1>

<div class="table-responsive backend">

<%= form_tag admin_songs_data_path, :method => 'get', :id => "songs_search" do %>
  <p>
    <%= link_to "Add Recording", new_ballad_path, class: "btn btn-primary file-button" %>
    <%= text_field_tag :search, params[:search], :class => "all-search form-control", :placeholder => "search" %>
  </p>
  
  <div id="songs"><%= render 'songs' %></div>

<% end %>

</div>

app/views/admin_pages/songs_data.js.erb
$("#songs").html("<%= escape_javascript(render("songs")) %>");