config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users

  resources :ballads do
    collection { post :import }
  end

  resources :ballad_imports

  resources :notifications, path: 'admin/notifications'

  get 'home' => 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'history' => 'static_pages#history'

  get 'links' => 'static_pages#links'

  get 'data' => 'data_vis#home'

  get 'data/popularity' => 'data_vis#popularity'

  get 'data/timeline' => 'data_vis#timeline'

  get 'all' => 'static_pages#all'

  get 'admin' => 'admin_pages#home'

  get 'admin/music-data' => 'admin_pages#music_data'

  get 'admin/ballad-data' => 'admin_pages#ballad_data'

  get 'admin/songs-data' => 'admin_pages#songs_data'

end

app/controllers/data_vis_controller.rb
class DataVisController < ApplicationController
    before_action :disable_nav
  
    def home
    end
  
    def popularity
      sql = "select cb.number, cb.name, COUNT(s.id) as ballad_count 
        from songs s 
        inner join child_ballads cb on cb.number = s.ballad_id 
        group by cb.number, cb.name 
        order by cb.number"
      @records_array = ActiveRecord::Base.connection.execute(sql)

      respond_to do |format|
        format.html
        format.json { render json: @records_array }
      end
    end
  
    def timeline
      sql = "select s.release_year, COUNT(s.id) as ballad_count 
        from songs s 
        where s.release_year is not null
        group by s.release_year 
        order by s.release_year"
      sql_array = ActiveRecord::Base.connection.execute(sql)
      @records_array = sql_array.select { |i| (1582..2500).include?(i['release_year'].to_i) && i['release_year'].length == 4 }

      respond_to do |format|
        format.html
        format.json { render json: @records_array }
      end
    end
  
    private
  
  end
  

app/views/data_vis/home.html.erb
<div class="intro-text">
    <h1>Data Analysis</h1>
    
    <div class="div-line"></div>

    <%= link_to "Popularity", data_popularity_path, class: "btn btn-primary begin-button" %>
    <%= link_to "Timeline", data_timeline_path, class: "btn btn-primary begin-button" %>
</div>

app/views/data_vis/popularity.html.erb
<%# Fix for javascript loading twice when turbolinks is on  %> 
<% content_for(:body_attributes) do %>
  data-turbolinks="false"
<% end %>

<%= link_to "Back", data_path, class: "btn btn-primary back-button" %>

<h1>Popularity</h1>

<div class="div-line"></div>

<div id="my_dataviz"></div>

<script type="text/javascript">
// set the dimensions and margins of the graph
var margin = {top: 70, right: 30, bottom: 100, left: 325},
    width = ($('.front-main').width()*.9) - margin.left - margin.right,
    height = 6000 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);


var loadData = function(){
  $.ajax({
    type: 'GET',
    contentType: 'application/json; charset=utf-8',
    url: '/data/popularity',
    dataType: 'json',
    success: function(data){
      drawChart(data);
    },
    failure: function(result){
      console.log(result)
    }
  });
};

// Parse the Data
function drawChart(data) {
  // X axis
  var x = d3.scaleLinear()
    .domain([0, Math.max.apply(Math, data.map(function(d) { return d.ballad_count; }))])
    .range([ 0, width]);
  svg.append("g")
    .call(d3.axisTop(x))
    .selectAll("text")
      .attr("transform", "translate(10,0)rotate(-45)")
      .style("text-anchor", "start");  

  // ----------------
  // Create a tooltip
  // ----------------
  var tooltip = d3.select("#my_dataviz")
    .append("div")
    .style("opacity", 0)
    .attr("class", "tooltip")
    .style("background-color", "white")
    .style("border", "solid")
    .style("border-width", "1px")
    .style("border-radius", "5px")
    .style("padding", "10px")
    .style("position", "fixed")

  // Three function that change the tooltip when user hover / move / leave a cell
  var mouseover = function(event, d) {
    var count = d.ballad_count;
    tooltip
        .html("Count: " + count)
        .style("opacity", 1)
        
  }
  var mousemove = function(event, d) {
    tooltip.style("left",(event.x)+20+"px")
           .style("top",(event.y)+"px")
  }
  var mouseleave = function(event, d) {
    tooltip
      .style("opacity", 0)
  }
  // ----------------

  // Add Y axis
  var y = d3.scaleBand()
    .range([ 0, height ])
    .domain(data.map(d => d.number+' - '+d.name))
    .padding(.1);
  svg.append("g")
    .call(d3.axisLeft(y))
    .selectAll("text")
      .data(data)
      .on("mouseover", mouseover)
      .on("mousemove", mousemove)
      .on("mouseleave", mouseleave)

  svg.selectAll("myRect")
    .data(data)
    .join("rect")
      .attr("x", x(0) )
      .attr("y", d => y(d.number+' - '+d.name))
      .attr("width", d => 0)
      .attr("height", y.bandwidth())
      .attr("fill", "#5a618a")
    .on("mouseover", mouseover)
    .on("mousemove", mousemove)
    .on("mouseleave", mouseleave)

  // Add X axis label:
  svg.append("text")
      .attr("text-anchor", "start")
      .attr("x", width/2-40)
      .attr("y", -50)
      .attr("font-size", "12px")
      .style("fill", "#333333")
      .text("Recording Count");

  // Animation
  svg.selectAll("rect")
    .transition()
    .duration(800)
    .attr("width", function(d) { return x(d.ballad_count); })
    .delay(function(d,i){return(i*10)})

}

loadData(); 

</script>

app/views/data_vis/timeline.html.erb
<%# Fix for javascript loading twice when turbolinks is on  %> 
<% content_for(:body_attributes) do %>
  data-turbolinks="false"
<% end %>

<%= link_to "Back", data_path, class: "btn btn-primary back-button" %>

<h1>Popularity</h1>

<div class="div-line"></div>

<div id="my_dataviz"></div>

<script type="text/javascript">
// set the dimensions and margins of the graph
var margin = {top: 30, right: 30, bottom: 70, left: 60},
    width = ($('.front-main').width()) - margin.left - margin.right,
    height = 400 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#my_dataviz")
  .append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

var loadData = function(){
  $.ajax({
    type: 'GET',
    contentType: 'application/json; charset=utf-8',
    url: '/data/timeline',
    dataType: 'json',
    success: function(data){
      drawChart(data);
    },
    failure: function(result){
      console.log(result)
    }
  });
};

// Parse the Data
function drawChart(data) {
    // X axis
    var x = d3.scaleBand()
    .range([ 0, width ])
    .domain(data.map(d => d.release_year))
    .padding(0.2);
    svg.append("g")
    .attr("transform", `translate(0, ${height})`)
    .call(d3.axisBottom(x).tickValues(x.domain().filter(function(d,i){ return !(i%2)})))
    .selectAll("text")
        .attr("transform", "translate(-10,0)rotate(-45)")
        .style("text-anchor", "end");

    // Add Y axis
    var y = d3.scaleLinear()
    .domain([0, Math.max.apply(Math, data.map(function(d) { return d.ballad_count; }))])
    .range([ height, 0]);
    svg.append("g")
    .call(d3.axisLeft(y));

    // ----------------
    // Create a tooltip
    // ----------------
    var tooltip = d3.select("#my_dataviz")
        .append("div")
        .style("opacity", 0)
        .attr("class", "tooltip")
        .style("background-color", "white")
        .style("border", "solid")
        .style("border-width", "1px")
        .style("border-radius", "5px")
        .style("padding", "10px")
        .style("position", "fixed")

    // Three function that change the tooltip when user hover / move / leave a cell
    var mouseover = function(event, d) {
        var count = d.ballad_count;
        tooltip
            .html("Year: " + d.release_year + "<br>" + "Count: " + count)
            .style("opacity", 1)
            
    }
    var mousemove = function(event, d) {
        tooltip.style("left",(event.x)+20+"px")
            .style("top",(event.y)+"px")
    }
    var mouseleave = function(event, d) {
        tooltip
        .style("opacity", 0)
    }
    // ----------------

    // Bars
    svg.selectAll("mybar")
    .data(data)
    .join("rect")
        .attr("x", d => x(d.release_year))
        .attr("y", d => y(0))
        .attr("width", x.bandwidth())
        .attr("height", d => height - y(0))
        .attr("fill", "#5a618a")
    .on("mouseover", mouseover)
    .on("mousemove", mousemove)
    .on("mouseleave", mouseleave)

    // Add X axis label:
    svg.append("text")
        .attr("text-anchor", "start")
        .attr("x", -190)
        .attr("y", -40)
        .attr("font-size", "12px")
        .style("fill", "#333333")
        .text("Recording Count")
    .attr("transform", "rotate(-90)");

    // Animation
    svg.selectAll("rect")
        .transition()
        .duration(800)
        .attr("y", function(d) { return y(d.ballad_count); })
        .attr("height", function(d) { return height - y(d.ballad_count); })
        .delay(function(d,i){return(i*10)})
}

loadData(); 

</script>