config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  devise_for :users

  resources :ballads do
    collection { post :import }
  end

  resources :ballad_imports

  resources :notifications, path: 'admin/notifications'

  get 'home' => 'static_pages#home'

  get 'contact' => 'static_pages#contact'

  get 'history' => 'static_pages#history'

  get 'links' => 'static_pages#links'

  get 'data' => 'data_vis#home'

  get 'data/popularity' => 'data_vis#popularity'

  get 'data/timeline' => 'data_vis#timeline'

  get 'all' => 'static_pages#all'

  get 'admin' => 'admin_pages#home'

  get 'admin/music-data' => 'admin_pages#music_data'

  get 'admin/ballad-data' => 'admin_pages#ballad_data'

  get 'admin/songs-data' => 'admin_pages#songs_data'

end

app/views/layouts/_footer.html.erb
<div class="footer bottom">
  <br>
  <div class="div-line"></div>
  <p class="top" ><%= link_to "Contact", contact_path %></p>
  <p><%= link_to "History", history_path %></p>
</div>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
        <ul class="nav navbar-nav">
          <li><%= link_to "Home", admin_path %></li>
          <li><%= link_to "Child Ballads", admin_music_data_path %></li>
          <li><%= link_to "All Songs", admin_songs_data_path %></li>
          <li><%= link_to "Bulk Data Tools", new_ballad_import_path %></li>
          <li><%= link_to "Notifications", notifications_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        </ul>
      <!-- </div> --><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %>

app/views/layouts/_navbarfront.html.erb
<nav class="navbar navbar-frontend">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> -->
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Recordings", all_path %></li>
      </ul>

      <% @notifications.each do |notification| %>
        <div class="site-notification"><%= notification.text %></div>
      <% end %>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Data", data_path %></li>
        <li><%= link_to "Resources", links_path %></li>
      </ul>
    <!-- </div> --><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CBDB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans|Open+Sans+Condensed:300|Noto+Serif" rel="stylesheet">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-52EEHVNN58"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-52EEHVNN58');
  </script>
</head>
<body 
  <% if content_for?(:body_attributes) %>
    <%= yield(:body_attributes) %> 
  <% end %>>

<%= render 'layouts/navbar' unless @disable_nav %>

<%= render 'layouts/navbarfront', notifications: @notifications if @disable_nav %>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<% if @disable_nav %>
  <div class="front-main">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
<% else %>
  <div class="main-container">
    <%= yield %>
  </div>
<% end %>

</body>
</html>